# Translate the numbers in the data into words

complete_dataE <- complete_data

complete_dataE$gender[complete_dataE$gender == "1"] <- "male."
complete_dataE$gender[complete_dataE$gender == "2"] <- "female."

complete_dataE$residence[complete_dataE$residence == "1"] <- "Keelung."
complete_dataE$residence[complete_dataE$residence == "2"] <- "Taipei"
complete_dataE$residence[complete_dataE$residence == "3"] <- "New Taipei City."
complete_dataE$residence[complete_dataE$residence == "4"] <- "Taoyuan."
complete_dataE$residence[complete_dataE$residence == "5"] <- "Hsinchu."
complete_dataE$residence[complete_dataE$residence == "6"] <- "Hsinchu County."
complete_dataE$residence[complete_dataE$residence == "7"] <- "Miaoli County."
complete_dataE$residence[complete_dataE$residence == "8"] <- "Taichung."
complete_dataE$residence[complete_dataE$residence == "9"] <- "Changhua County."
complete_dataE$residence[complete_dataE$residence == "10"] <- "Nantou County."
complete_dataE$residence[complete_dataE$residence == "11"] <- "Yunlin County."
complete_dataE$residence[complete_dataE$residence == "12"] <- "Chiayi."
complete_dataE$residence[complete_dataE$residence == "13"] <- "Chiayi County."
complete_dataE$residence[complete_dataE$residence == "14"] <- "Tainan City."
complete_dataE$residence[complete_dataE$residence == "15"] <- "Kaohsiung."
complete_dataE$residence[complete_dataE$residence == "16"] <- "Pingtung County."
complete_dataE$residence[complete_dataE$residence == "17"] <- "Taitung County."
complete_dataE$residence[complete_dataE$residence == "18"] <- "Hualien County."
complete_dataE$residence[complete_dataE$residence == "19"] <- "Yilan County."
complete_dataE$residence[complete_dataE$residence == "20"] <- "Penghu County."
complete_dataE$residence[complete_dataE$residence == "21"] <- "Kinmen."
complete_dataE$residence[complete_dataE$residence == "96"] <- "a rare place."

complete_dataE$father[complete_dataE$father == "1"] <- "a Taiwanese from Fujian Minnan"
complete_dataE$father[complete_dataE$father == "2"] <- "a Taiwanese from Guangdong Hakka"
complete_dataE$father[complete_dataE$father == "3"] <- "a Taiwanese from Mainland"
complete_dataE$father[complete_dataE$father == "4"] <- "a Taiwan Aborigine"
complete_dataE$father[complete_dataE$father == "5"] <- "a resident of Chinese citizenship"
complete_dataE$father[complete_dataE$father == "6"] <- "a Southeast Asian"
complete_dataE$father[complete_dataE$father == "7"] <- "one from rare groups"

complete_dataE$mother[complete_dataE$mother == "1"] <- "a Taiwanese from Fujian Minnan."
complete_dataE$mother[complete_dataE$mother == "2"] <- "a Taiwanese from Guangdong Hakka."
complete_dataE$mother[complete_dataE$mother == "3"] <- "a Taiwanese from Mainland."
complete_dataE$mother[complete_dataE$mother == "4"] <- "a Taiwan Aborigine."
complete_dataE$mother[complete_dataE$mother == "5"] <- "a resident of Chinese citizenship."
complete_dataE$mother[complete_dataE$mother == "6"] <- "a Southeast Asian."
complete_dataE$mother[complete_dataE$mother == "7"] <- "one from rare groups."

complete_dataE$education[complete_dataE$education %in% c(1, 2, 3)] <- "primary school degree or lower"
complete_dataE$education[complete_dataE$education %in% c(4, 5)] <- "middle school degree"
complete_dataE$education[complete_dataE$education %in% c(6, 7, 8)] <- "high school degree"
complete_dataE$education[complete_dataE$education %in% c(9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)] <- "college degree"

complete_dataE$religion[complete_dataE$religion %in% c(1, 2)] <- "very religious."
complete_dataE$religion[complete_dataE$religion %in% c(3, 4)] <- "somewhat religious."
complete_dataE$religion[complete_dataE$religion %in% c(5, 6)] <- "not very religious."
complete_dataE$religion[complete_dataE$religion %in% c(7, 8)] <- "not religious at all."

complete_dataE$democracy[complete_dataE$democracy %in% c(0, 1)] <- "think it’s very low."
complete_dataE$democracy[complete_dataE$democracy %in% c(2, 3)] <- "think it’s fairly low."
complete_dataE$democracy[complete_dataE$democracy %in% c(4, 5, 6)] <- "think it’s moderate."
complete_dataE$democracy[complete_dataE$democracy %in% c(7, 8)] <- "think it’s fairly high."
complete_dataE$democracy[complete_dataE$democracy %in% c(9, 10)] <- "think it’s very high."
complete_dataE$democracy[complete_dataE$democracy %in% c(93)] <- "have no opinion."

complete_dataE$identification[complete_dataE$identification == "1"] <- "Taiwanese"
complete_dataE$identification[complete_dataE$identification == "2"] <- "Chinese"
complete_dataE$identification[complete_dataE$identification == "3"] <- "Taiwanese and Chinese"
complete_dataE$identification[complete_dataE$identification == "4"] <- "Chinese and Taiwanese"
complete_dataE$identification[complete_dataE$identification == "5"] <- "neither Taiwanese nor Chinese"

complete_dataE$relationship[complete_dataE$relationship == "1"] <- "suggest to unify with Mainland China."
complete_dataE$relationship[complete_dataE$relationship == "2"] <- "suggest to become independent."
complete_dataE$relationship[complete_dataE$relationship == "3"] <- "suggest to maintain the status quo."
complete_dataE$relationship[complete_dataE$relationship == "4"] <- "think it depends on the situation."
complete_dataE$relationship[complete_dataE$relationship == "93"] <- "have no comment."

complete_dataE$party[complete_dataE$party == "1"] <- "the Kuomintang / Chinese Nationalist Party."
complete_dataE$party[complete_dataE$party == "2"] <- "the Democratic Progressive Party."
complete_dataE$party[complete_dataE$party == "3"] <- "the People First Party."
complete_dataE$party[complete_dataE$party == "4"] <- "the Taiwan Solidarity Union."
complete_dataE$party[complete_dataE$party == "5"] <- "the New Party."
complete_dataE$party[complete_dataE$party == "6"] <- "the New Power Party."
complete_dataE$party[complete_dataE$party == "7"] <- "the Taiwan People's Party."
complete_dataE$party[complete_dataE$party == "8"] <- "the Green Party."
complete_dataE$party[complete_dataE$party == "9"] <- "the Taiwan Statebuilding Party."
complete_dataE$party[complete_dataE$party == "10"] <- "all."
complete_dataE$party[complete_dataE$party == "11"] <- "neither of them."

complete_dataE$employment[complete_dataE$employment %in% c(1)] <- "working"
complete_dataE$employment[complete_dataE$employment %in% c(2, 4, 5, 6)] <- "not working"
complete_dataE$employment[complete_dataE$employment %in% c(3)] <- "studying/training"

complete_dataE$social[complete_dataE$social %in% c(1, 2, 3)] <- "low."
complete_dataE$social[complete_dataE$social %in% c(4, 5, 6, 7)] <- "middle."
complete_dataE$social[complete_dataE$social %in% c(8, 9, 10)] <- "high."

complete_dataE$election[complete_dataE$election == "1"] <- "Soong Chu-yu"
complete_dataE$election[complete_dataE$election == "2"] <- "Han Kuo-yu"
complete_dataE$election[complete_dataE$election == "3"] <- "Tsai Ing-wen"
complete_dataE$election[complete_dataE$election == "4"] <- "invalid vote"
complete_dataE$election[complete_dataE$election == "6"] <- "did not vote"

