complete_dataT <- complete_data

complete_dataT$gender[complete_dataT$gender == "1"] <- "男"
complete_dataT$gender[complete_dataT$gender == "2"] <- "女"

complete_dataT$residence[complete_dataT$residence == "1"] <- "基隆市。"
complete_dataT$residence[complete_dataT$residence == "2"] <- "臺北市。"
complete_dataT$residence[complete_dataT$residence == "3"] <- "新北市。"
complete_dataT$residence[complete_dataT$residence == "4"] <- "桃園市。"
complete_dataT$residence[complete_dataT$residence == "5"] <- "新竹市。"
complete_dataT$residence[complete_dataT$residence == "6"] <- "新竹縣。"
complete_dataT$residence[complete_dataT$residence == "7"] <- "苗栗縣。"
complete_dataT$residence[complete_dataT$residence == "8"] <- "台中市。"
complete_dataT$residence[complete_dataT$residence == "9"] <- "彰化縣。"
complete_dataT$residence[complete_dataT$residence == "10"] <- "南投縣。"
complete_dataT$residence[complete_dataT$residence == "11"] <- "雲林縣。"
complete_dataT$residence[complete_dataT$residence == "12"] <- "嘉義市。"
complete_dataT$residence[complete_dataT$residence == "13"] <- "嘉義縣。"
complete_dataT$residence[complete_dataT$residence == "14"] <- "台南市。"
complete_dataT$residence[complete_dataT$residence == "15"] <- "高雄市。"
complete_dataT$residence[complete_dataT$residence == "16"] <- "屏東縣。"
complete_dataT$residence[complete_dataT$residence == "17"] <- "台東縣"
complete_dataT$residence[complete_dataT$residence == "18"] <- "花蓮縣。"
complete_dataT$residence[complete_dataT$residence == "19"] <- "宜蘭縣。"
complete_dataT$residence[complete_dataT$residence == "20"] <- "澎湖縣。"
complete_dataT$residence[complete_dataT$residence == "21"] <- "金門縣。"
complete_dataT$residence[complete_dataT$residence == "96"] <- "其他偏僻的地方。"

complete_dataT$father[complete_dataT$father == "1"] <- "臺灣閩南人，"
complete_dataT$father[complete_dataT$father == "2"] <- "臺灣客家人，"
complete_dataT$father[complete_dataT$father == "3"] <- "大陸各省市（外省）人，"
complete_dataT$father[complete_dataT$father == "4"] <- "臺灣原住民，"
complete_dataT$father[complete_dataT$father == "5"] <- "大陸籍，"
complete_dataT$father[complete_dataT$father == "6"] <- "東南亞籍，"
complete_dataT$father[complete_dataT$father == "7"] <- "非常見民族，"

complete_dataT$mother[complete_dataT$mother == "1"] <- "臺灣閩南人。"
complete_dataT$mother[complete_dataT$mother == "2"] <- "臺灣客家人。"
complete_dataT$mother[complete_dataT$mother == "3"] <- "大陸各省市（外省）人。"
complete_dataT$mother[complete_dataT$mother == "4"] <- "臺灣原住民。"
complete_dataT$mother[complete_dataT$mother == "5"] <- "大陸籍。"
complete_dataT$mother[complete_dataT$mother == "6"] <- "東南亞籍。"
complete_dataT$mother[complete_dataT$mother == "7"] <- "非常見民族。"

complete_dataT$education[complete_dataT$education %in% c(1, 2, 3)] <- "小學畢業或以下，"
complete_dataT$education[complete_dataT$education %in% c(4, 5)] <- "初中畢業，"
complete_dataT$education[complete_dataT$education %in% c(6, 7, 8)] <- "高中畢業，"
complete_dataT$education[complete_dataT$education %in% c(9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)] <- "高等教育，"

complete_dataT$religion[complete_dataT$religion %in% c(1, 2)] <- "非常虔誠"
complete_dataT$religion[complete_dataT$religion %in% c(3, 4)] <- "比較虔誠"
complete_dataT$religion[complete_dataT$religion %in% c(5, 6)] <- "不太虔誠"
complete_dataT$religion[complete_dataT$religion %in% c(7, 8)] <- "不"

complete_dataT$democracy[complete_dataT$democracy %in% c(0, 1)] <- "認為非常低。"
complete_dataT$democracy[complete_dataT$democracy %in% c(2, 3)] <- "認為比較低。"
complete_dataT$democracy[complete_dataT$democracy %in% c(4, 5, 6)] <- "認為一般。"
complete_dataT$democracy[complete_dataT$democracy %in% c(7, 8)] <- "認為比較高。"
complete_dataT$democracy[complete_dataT$democracy %in% c(9, 10)] <- "認為非常高。"
complete_dataT$democracy[complete_dataT$democracy %in% c(93)] <- "無意見。"

complete_dataT$identification[complete_dataT$identification == "1"] <- "是臺灣人，"
complete_dataT$identification[complete_dataT$identification == "2"] <- "是中國人，"
complete_dataT$identification[complete_dataT$identification == "3"] <- "是臺灣人和中國人，"
complete_dataT$identification[complete_dataT$identification == "4"] <- "是中國人和臺灣人，"
complete_dataT$identification[complete_dataT$identification == "5"] <- "既不是臺灣人也不是中國人，"

complete_dataT$relationship[complete_dataT$relationship == "1"] <- "支持統一。"
complete_dataT$relationship[complete_dataT$relationship == "2"] <- "支持獨立。"
complete_dataT$relationship[complete_dataT$relationship == "3"] <- "支持維持現狀。"
complete_dataT$relationship[complete_dataT$relationship == "4"] <- "認為要看情形。"
complete_dataT$relationship[complete_dataT$relationship == "93"] <- "無意見。"

complete_dataT$party[complete_dataT$party == "1"] <- "支持國民黨。"
complete_dataT$party[complete_dataT$party == "2"] <- "支持民進黨。"
complete_dataT$party[complete_dataT$party == "3"] <- "支持親民黨。"
complete_dataT$party[complete_dataT$party == "4"] <- "支持台聯。"
complete_dataT$party[complete_dataT$party == "5"] <- "支持新黨。"
complete_dataT$party[complete_dataT$party == "6"] <- "支持時代力量。"
complete_dataT$party[complete_dataT$party == "7"] <- "支持臺灣民眾黨。"
complete_dataT$party[complete_dataT$party == "8"] <- "支持綠黨。"
complete_dataT$party[complete_dataT$party == "9"] <- "支持臺灣激進。"
complete_dataT$party[complete_dataT$party == "10"] <- "都支持。"
complete_dataT$party[complete_dataT$party == "11"] <- "都不支持。"

complete_dataT$employment[complete_dataT$employment %in% c(1)] <- "工作，"
complete_dataT$employment[complete_dataT$employment %in% c(2, 4, 5, 6)] <- "不工作，"
complete_dataT$employment[complete_dataT$employment %in% c(3)] <- "studying/training，"

complete_dataT$social[complete_dataT$social %in% c(1, 2, 3)] <- "底層。"
complete_dataT$social[complete_dataT$social %in% c(4, 5, 6, 7)] <- "中層。"
complete_dataT$social[complete_dataT$social %in% c(8, 9, 10)] <- "高層。"

complete_dataT$election[complete_dataT$election == "1"] <- "宋楚瑜"
complete_dataT$election[complete_dataT$election == "2"] <- "韓國瑜"
complete_dataT$election[complete_dataT$election == "3"] <- "蔡英文"
complete_dataT$election[complete_dataT$election == "4"] <- "投廢票"
complete_dataT$election[complete_dataT$election == "6"] <- "沒有投票"
